### ISSUE TITLE
Create styles for breakpoint(s) <768px

### ISSUE THREAD

**Issue by ktbartholomew** [rackerlabs/docs-redesign-prototype#1]
A single set of styles below 768px could work, but we might want to add another breakpoint at ~480px for the mini tablet users.

Use mobile-first CSS rule ordering:

```less
.docs-content {
    /* styles for 320px and up */
    background: rgba(255,0,0,0.2);

    @media (min-width: 481px) {
        background: rgba(255,0,0,0.4);
    }

    @media (min-width: 769px) {
        background: rgba(255,0,0,0.6);
    }

    @media (min-width: 1025px) {
        background: rgba(255,0,0,0.8);
    }
}
```
